name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:buster

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash .github/build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          target/release/portknock
        retention-days: 90
  
